name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
  - python=3.9.0
=======
  - python=3.10.0
>>>>>>> 1e77042edab3699d34e71c3fd4380d5d780b5b29
  - pandas=2.1.3
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
