wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724791873.753705
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
random_seed:
  desc: null
  value: 42
stratify_by:
  desc: null
  value: neighbourhood_group
rf_config:
  desc: null
  value: rf_config
max_tfidf_features:
  desc: null
  value: 5
output_artifact:
  desc: null
  value: random_forest_export
